//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EmployeePostInfo
    {
        public int EmployeePostInfoId { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> HoursPerWeek { get; set; }
        public Nullable<int> Department_id { get; set; }
        public Nullable<int> Job_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }


        public int Pros
        { 
            get
            {
                return Employee.Reviews.Where(r => r.IsGoodReview == true).Count();
            }
        }
        public int Cons
        {
            get
            {
                return Employee.Reviews.Where(r => r.IsGoodReview == false).Count();
            }
        }
    }
}
